services:
  web:
    build: .
    image: haxx616/hellonode:latest   # optional: tag for Docker Hub
    container_name: node-web-app
    ports:
      - "3000:3000"   # host:container
    restart: unless-stopped
